name    'biemond-jdksolaris'
version '0.1.0'
source ''
author 'Edwin Biemond'
license 'Apache 2.0'
summary 'Oracle JDK7 puppet module for Oracle Solaris 10'
description 'Oracle JDK7 puppet module for Oracle Solaris 10'
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
